In [1]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
indices = np.array([[0, 2], [1, 1]])
result = arr[indices]
print(result)  # 输出: [[1 3], [5 5]]


[[[1 2 3]
  [7 8 9]]

 [[4 5 6]
  [4 5 6]]]


In [2]:
index_arr = np.array([1, 3])
row_index, col_index = index_arr
print(row_index, col_index)

1 3


In [4]:
import torch

# 创建一个输入张量
input = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 创建一个索引张量
index = torch.tensor([[0, 1], [2, 0]])

# 获取对应位置的内容
output = input[index[:, 0], index[:, 1]]

print(output)


tensor([2, 7])
